### ISSUE TITLE
How to get exit code on catch/fail

### ISSUE THREAD

**Issue by DanilloCorvalan** [tunnckoCore/exec-cmd#3]
How do you get exit code on catch, the err object doesn't come with it

**Comment by DanilloCorvalan** [comment]
sorry, didn't see that

`
 err.status
`

**Comment by tunnckoCore** [comment]
@DanilloCorvalan  Ha, sorry for the delay. But yes, `async-exec-cmd` does not do anything special.
I should refactor it soon.

**Comment by tunnckoCore** [comment]
By the way, I'm just curios, do you like `hybrids` idea behind [hybridify](https://github.com/hybridables/hybridify) and that org?

**Comment by DanilloCorvalan** [comment]
@tunnckoCore I found it great! I use it in a promise way.
